### Register a new association
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "nombre": "Test Association",
  "email": "association@example.com",
  "password": "password123",
  "ciudad": "La Mojonera",
  "pais": "Test Country"
}

### Login to get a JWT token
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "association@example.com",
  "password": "password123"
}

### Create a new socio
POST http://localhost:3001/api/socio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhkMGY4ZDc1NTNhNDYwNzNjMDMzMDEiLCJsb2ciOiJhc3NvY2lhdGlvbiIsImlhdCI6MTcyMDUyMjQ1NiwiZXhwIjoxNzIwNTI5NjU2fQ.Vk99ZnkvhrZw67sa1psY49rmNqYOOXotajbStDhQzNo

{
  "nombre": "Test Socio",
  "apellidos": "Socio Apellidos",
  "telefono": "123456789",
  "direccion": "Calle Falsa 123",
  "foto": "http://example.com/foto.jpg",
  "asociacion": "668d0f8d7553a46073c03301"
}

### Update a socio
PUT http://localhost:3001/api/socio/668d129fbe161691314038fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhkMGY4ZDc1NTNhNDYwNzNjMDMzMDEiLCJsb2ciOiJhc3NvY2lhdGlvbiIsImlhdCI6MTcyMDUyMTE4OSwiZXhwIjoxNzIwNTI4Mzg5fQ.R2zIPFfLWWR_espN8603pdLmAWC_2leUWRix-OocK5E

{
  "nombre": "Updated Socio",
  "apellidos": "Updated Apellidos"
}

### Delete a socio
DELETE http://localhost:3001/api/socio/668d129fbe161691314038fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhkMGY4ZDc1NTNhNDYwNzNjMDMzMDEiLCJsb2ciOiJhc3NvY2lhdGlvbiIsImlhdCI6MTcyMDUyMTE4OSwiZXhwIjoxNzIwNTI4Mzg5fQ.R2zIPFfLWWR_espN8603pdLmAWC_2leUWRix-OocK5E

### Get a PDF with socio's information
GET http://localhost:3001/api/socio/668d16e8be16169131403903/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhkMGY4ZDc1NTNhNDYwNzNjMDMzMDEiLCJsb2ciOiJhc3NvY2lhdGlvbiIsImlhdCI6MTcyMDUyMjk0MCwiZXhwIjoxNzIwNTMwMTQwfQ.KThKbf9Ww9YMT5WQQ4dsuC0OJ8M4yiijx_5odYqtbK0

### Get a carnet with socio's information
GET http://localhost:3001/api/socio/668d16e8be16169131403903/carnet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhkMGY4ZDc1NTNhNDYwNzNjMDMzMDEiLCJsb2ciOiJhc3NvY2lhdGlvbiIsImlhdCI6MTcyMDUyMjk0MCwiZXhwIjoxNzIwNTMwMTQwfQ.KThKbf9Ww9YMT5WQQ4dsuC0OJ8M4yiijx_5odYqtbK0